version: '3'
services:
  php-apache:
    container_name: php-apache
    build: ./php-apache
    ports:
      - "80:80"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ../:/var/www/app:cached
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DB}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql:delegated
      - ./db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      # initial script
      # - ./mysql/sql:/docker-entrypoint-initdb.d

volumes:
  db:

